language: rust
cache: cargo
matrix:
  include:
  - os: linux
    rust: stable
    sudo: required
    before_script:
    - nvm install 10
    - npm install -g npx
    - rustup target add wasm32-unknown-unknown
    - cargo list | grep install-update || cargo install -f cargo-update
    - cargo install-update -i wasm-bindgen-cli
    - sudo apt-get update
    - sudo apt-get -y install python3 python3-pip
  - os: osx
    rust: stable
script:
- scripts/build-cherenkov.sh
deploy:
  - provider: s3
    skip_cleanup: true
    bucket: files.gridbugs.org
    region: ap-southeast-2
    local-dir: uploads
    acl: public_read
    on:
      all_branches: true
      repo: stevebob/cherenkov
      condition: "$TRAVIS_RUST_VERSION = stable"
    access_key_id: AKIAJTZWT26OECTU2UVQ
    secret_access_key:
      secure: YWb1lJ5DOFc3VOHMIPbfupsywMmkjGGVxrKaNYn5NbSfF2L/MG3ltop1QwaBjMe1OLIIT7fLYMgZDE/UgLOo8yr2HxHNM1B3BVatACtwtF7jXE69+FPW9Lxpm8bc0SMTebNArsv012yP7k31ZbhvvpR1fwP4GIK8v1MJuRyUP4+uQlnHU2VwWirlvCu76+ZczQKz6UftygnItNBQGl1Yzt2JVHNGjAZ2KN779nxaTGzWz4XETKvzq1J3LmqOZN8RsK4EAGLLOYn94UpwWeuU9XGBXgFd5Mu08KX85s6k5yFMViBVk7R5k+urSiHMyOtvt/K+POuogENT3MJv5W2so01f2RTY326hhKxnrNbRyzCDfr9bwLxhob/6OYGKcD0pDxyAeIXZkrKdEkGOzRW/qeWOv3Rc5uIr+Qz/JRuy6QYncawYLh4HPxI7yyV08kUjrr08YhM+GGkTGLRyLX8JuuX5Cj3kzf9dAmlR9oz8fwJXzRMNvW287E111RJuF+DWjl8q1sB8K+VkKRNB3P7GjkIbZ298XtFrlmEaWD0GZjQpg9IdlrS6FcvTEw476Tm/5utQKvTLxedRXw/vcnRgHR6weRDK16MkxTS+GkrmtkPYNlFV+57jn81Mt+8uiCdjbXscSjM+BaCl/Eh3jmZNzFGKAdnY56TbNQRgYonYTVk=
  - provider: s3
    skip_cleanup: true
    bucket: games.gridbugs.org
    region: ap-southeast-2
    local-dir: web_uploads
    acl: public_read
    on:
      all_branches: true
      repo: stevebob/cherenkov
      condition: "$TRAVIS_RUST_VERSION = stable"
      condition: "$TRAVIS_OS_NAME = linux"
    access_key_id: AKIAJTZWT26OECTU2UVQ
    secret_access_key:
      secure: YWb1lJ5DOFc3VOHMIPbfupsywMmkjGGVxrKaNYn5NbSfF2L/MG3ltop1QwaBjMe1OLIIT7fLYMgZDE/UgLOo8yr2HxHNM1B3BVatACtwtF7jXE69+FPW9Lxpm8bc0SMTebNArsv012yP7k31ZbhvvpR1fwP4GIK8v1MJuRyUP4+uQlnHU2VwWirlvCu76+ZczQKz6UftygnItNBQGl1Yzt2JVHNGjAZ2KN779nxaTGzWz4XETKvzq1J3LmqOZN8RsK4EAGLLOYn94UpwWeuU9XGBXgFd5Mu08KX85s6k5yFMViBVk7R5k+urSiHMyOtvt/K+POuogENT3MJv5W2so01f2RTY326hhKxnrNbRyzCDfr9bwLxhob/6OYGKcD0pDxyAeIXZkrKdEkGOzRW/qeWOv3Rc5uIr+Qz/JRuy6QYncawYLh4HPxI7yyV08kUjrr08YhM+GGkTGLRyLX8JuuX5Cj3kzf9dAmlR9oz8fwJXzRMNvW287E111RJuF+DWjl8q1sB8K+VkKRNB3P7GjkIbZ298XtFrlmEaWD0GZjQpg9IdlrS6FcvTEw476Tm/5utQKvTLxedRXw/vcnRgHR6weRDK16MkxTS+GkrmtkPYNlFV+57jn81Mt+8uiCdjbXscSjM+BaCl/Eh3jmZNzFGKAdnY56TbNQRgYonYTVk=
