language: rust
matrix:
  include:
  - os: linux
    rust: stable
  - os: osx
    rust: stable
before_script:
  - npm install -g npx
  - rustup target add wasm32-unknown-unknown
  - cargo install -f wasm-bindgen-cli
script:
- scripts/build-cherenkov.sh
