[package]
name = "cherenkov"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
serde = { version = "1.0", features = ["serde_derive"] }
